/**
 * mockData.ts
 * Initial seeded database rates, listings, users, and conversations.
 */

import { UserProfile, VegetableListing, Order, KalimatiRate } from './types';

// Standard Users
export const MOCK_USERS: UserProfile[] = [
  {
    id: 'farmer_pema',
    name: 'Pema Shrestha',
    role: 'FARMER',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    district: 'Panchkhal, Kavre',
    phone: '+977-9851012345',
    companyName: 'Panchkhal organic growers co-op',
    rating: 4.8,
    totalDeals: 42,
  },
  {
    id: 'farmer_manoj',
    name: 'Manoj Dahal',
    role: 'FARMER',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    district: 'Benighat, Dhading',
    phone: '+977-9841234567',
    companyName: 'Dhading Vegetable Hub',
    rating: 4.6,
    totalDeals: 29,
  },
  {
    id: 'farmer_sonam',
    name: 'Sonam Gurung',
    role: 'FARMER',
    avatar: 'https://images.unsplash.com/photo-1489980508314-941910ded1f4?w=150&auto=format&fit=crop&q=80',
    district: 'Marpha, Mustang',
    phone: '+977-9856098765',
    companyName: 'Marpha High-Altitude Orchards',
    rating: 4.9,
    totalDeals: 34,
  },
  {
    id: 'farmer_bikas',
    name: 'Bikas Adhikari',
    role: 'FARMER',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    district: 'Ilam, Eastern Nepal',
    phone: '+977-9801230987',
    companyName: 'Ilam Organics tea & Spices',
    rating: 4.7,
    totalDeals: 51,
  },
  {
    id: 'wholesaler_ramesh',
    name: 'Ramesh Traders',
    role: 'WHOLESALER',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    district: 'Kalimati, Kathmandu',
    phone: '+977-9803123456',
    companyName: 'Ramesh Fruits & Veg Wholesalers Ltd.',
    rating: 4.9,
    totalDeals: 118,
  },
  {
    id: 'admin_sys',
    name: 'BizzLedger Desk',
    role: 'ADMIN',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    district: 'Teku, Kathmandu',
    phone: '+977-1-4211111',
    rating: 5.0,
    totalDeals: 0,
  }
];

// Today's official Kalimati Market wholesale rates (estimates)
export const KALIMATI_RATES: KalimatiRate[] = [
  { cropName: 'Tomato (Local)', minPrice: 75, maxPrice: 90, avgPrice: 82, unit: 'KG', change: 'up' },
  { cropName: 'Potato (Red)', minPrice: 50, maxPrice: 58, avgPrice: 54, unit: 'KG', change: 'down' },
  { cropName: 'Cabbage', minPrice: 35, maxPrice: 45, avgPrice: 40, unit: 'KG', change: 'stable' },
  { cropName: 'Cauliflower (Local)', minPrice: 95, maxPrice: 115, avgPrice: 105, unit: 'KG', change: 'up' },
  { cropName: 'Okra (Bhindi)', minPrice: 80, maxPrice: 90, avgPrice: 85, unit: 'KG', change: 'down' },
  { cropName: 'Bitter Gourd (Tite Karela)', minPrice: 70, maxPrice: 80, avgPrice: 75, unit: 'KG', change: 'stable' },
  { cropName: 'Onion (Dry)', minPrice: 85, maxPrice: 95, avgPrice: 90, unit: 'KG', change: 'up' },
  { cropName: 'Carrot (Local)', minPrice: 65, maxPrice: 75, avgPrice: 70, unit: 'KG', change: 'stable' },
  { cropName: 'Radish (White)', minPrice: 30, maxPrice: 38, avgPrice: 34, unit: 'KG', change: 'down' },
];

export const INITIAL_LISTINGS: VegetableListing[] = [
  {
    id: 'list_seed_001',
    cropName: 'Red Tomatoes (Hybrid)',
    category: 'Tomatoes',
    district: 'Panchkhal, Kavre',
    farmerId: 'farmer_pema',
    farmerName: 'Pema Shrestha',
    farmerRating: 4.8,
    quantityAvailableCrates: 120,
    pricePerCrate: 1600,
    harvestDate: '2026-07-20',
    readyToShip: true,
    notes: 'Organically grown, pesticide-free. Suitable for hotels and restaurants.',
    imageUrl: 'https://images.unsplash.com/photo-1546094096-0df4bcabd337?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'list_seed_002',
    cropName: 'Mountain Potatoes (Red)',
    category: 'Potatoes',
    district: 'Benighat, Dhading',
    farmerId: 'farmer_manoj',
    farmerName: 'Manoj Dahal',
    farmerRating: 4.6,
    quantityAvailableCrates: 200,
    pricePerCrate: 1100,
    harvestDate: '2026-07-18',
    readyToShip: true,
    notes: 'High altitude potatoes. Starchy and perfect for curry. Fresh batch.',
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'list_seed_003',
    cropName: 'Fresh Cabbage (Large)',
    category: 'Cabbages',
    district: 'Panchkhal, Kavre',
    farmerId: 'farmer_pema',
    farmerName: 'Pema Shrestha',
    farmerRating: 4.8,
    quantityAvailableCrates: 80,
    pricePerCrate: 850,
    harvestDate: '2026-07-22',
    readyToShip: true,
    notes: 'Large round cabbages. Crisp and green. Ideal for wholesale vegetable shops.',
    imageUrl: 'https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'list_seed_004',
    cropName: 'Mustang Red Apples',
    category: 'Fruits',
    district: 'Marpha, Mustang',
    farmerId: 'farmer_sonam',
    farmerName: 'Sonam Gurung',
    farmerRating: 4.9,
    quantityAvailableCrates: 60,
    pricePerCrate: 3800,
    harvestDate: '2026-07-15',
    readyToShip: true,
    notes: 'Premium high-altitude Mustang apples. Sweet, juicy, and very popular in Kathmandu markets.',
    imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'list_seed_005',
    cropName: 'Organic Ginger (Adhuwa)',
    category: 'Spices',
    district: 'Ilam, Eastern Nepal',
    farmerId: 'farmer_bikas',
    farmerName: 'Bikas Adhikari',
    farmerRating: 4.7,
    quantityAvailableCrates: 45,
    pricePerCrate: 2200,
    harvestDate: '2026-07-19',
    readyToShip: true,
    notes: 'Pure organic ginger from Ilam. Strong aroma. Used by spice exporters and tea estates.',
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'list_seed_006',
    cropName: 'Cauliflower (Local White)',
    category: 'Cauliflower',
    district: 'Benighat, Dhading',
    farmerId: 'farmer_manoj',
    farmerName: 'Manoj Dahal',
    farmerRating: 4.6,
    quantityAvailableCrates: 95,
    pricePerCrate: 1950,
    harvestDate: '2026-07-21',
    readyToShip: true,
    notes: 'Large, tight white heads. No yellow discoloration. Direct from Dhading farms.',
    imageUrl: 'https://images.unsplash.com/photo-1568584711271-6c929fb49b60?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'list_seed_007',
    cropName: 'Ilam Cardamom (Alaichi)',
    category: 'Spices',
    district: 'Ilam, Eastern Nepal',
    farmerId: 'farmer_bikas',
    farmerName: 'Bikas Adhikari',
    farmerRating: 4.7,
    quantityAvailableCrates: 20,
    pricePerCrate: 8500,
    harvestDate: '2026-07-10',
    readyToShip: true,
    notes: 'Premium large-pod cardamom from Ilam hills. Grade A export quality. Limited stock.',
    imageUrl: 'https://images.unsplash.com/photo-1603145733146-ae562a55031e?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'list_seed_008',
    cropName: 'Spinach (Palungo) Bundle',
    category: 'Greens',
    district: 'Panchkhal, Kavre',
    farmerId: 'farmer_pema',
    farmerName: 'Pema Shrestha',
    farmerRating: 4.8,
    quantityAvailableCrates: 50,
    pricePerCrate: 700,
    harvestDate: '2026-07-23',
    readyToShip: true,
    notes: 'Tender dark green spinach. Freshly harvested this morning. Short shelf life, buy fast.',
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_ORDERS: Order[] = [];
